# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-05-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(max_length=20, unique=True)),
                ('full_name', models.TextField(max_length=50)),
                ('company', models.TextField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=40)),
                ('phone_number', models.TextField(max_length=17)),
                ('note', models.TextField(blank=True, max_length=256)),
            ],
        ),
    ]
